apiVersion: v1
kind: Pod
metadata:
  name: vitrola
spec:
  containers:
  - name: vi
    image: ubuntu
    args:
    - sleep
    - infinity
    volumeMounts:
    - name: first-emptydir
      mountPath: /vitrola
  volumes:
  - name: first-emptydir
    emptyDir:
      sizeLimit: 256Mi
