apiVersion: v1
kind: Pod
metadata:
  name: vitrola
labels:
  run: vitrola
spec:
  containers:
  - name: vi
    image: nginx
    ports:
    - containerPort: 80
  - name: trola
    image: alpine
    args:
    - sleep
    - "1800"
