apiVersion: v1
kind: Pod
metadata:
  name: vitrola-ubuntu
labels:
  run: vitrola-ubuntu
spec:
  containers:
  - name: vitrola-ubuntu
    image: ubuntu
    args:
    - sleep
    - infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.3"
