apiVersion: v1
kind: Pod
metadata:
  name: vitrola-emptydir
spec:
  containers:
  - name: vitrola-emptydir
    image: ubuntu
    args:
    - sleep
    - infinity
    volumeMounts:
    - name: first-empty
      mountPath: /vitrola
  volumes:
  - name: first-empty
    emptyDir:
      sizeLimit: 256Mi
